
---
- name: Install lemp stack
  hosts: all
  become: true
  
  tasks:
   - name: Add repository
     yum_repository:
       name: mysql-server
       description: mysql repo
       baseurl: http://repo.mysql.com/yum/mysql-5.6-community/el/6/$basearch/

   - name: Install LEMP Packages
     yum: name={{ item }} update_cache=yes state=latest
     loop: [ 'nginx', 'mysql-server', 'php-fpm', 'php-mysql' ]

# Handlers

   - name: Reload Nginx
     service:
       name: nginx
       state: reloaded

   - name: Restart Nginx
     service:
       name: nginx
       state: restarted
